server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
myCustomVar:
  welcomeMsg: Hello from Prod
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: test
myCustomVar:
  welcomeMsg: Hello from Test
server:
  port: 4000